### ISSUE TITLE
建议换个更容易记的名字

### ISSUE THREAD

**Issue by oahzuw** [ZihanType/predawn#1]
更容易记的名字成功90%。

**Comment by ZihanType** [comment]
名字是个见仁见智事，要好记、要短、要不和现有的冲突，目前这个名字是我比较满意的，或者你可以提出一些名字，我们比较一下。

**Comment by oahzuw** [comment]
ink
ink web
我也不会起名字

**Comment by ZihanType** [comment]
可惜这个名字已经被用了，[ink](https://github.com/paritytech/ink)
