### ISSUE TITLE
建议和axum或者actix-web集成，而不是自己造轮子

### ISSUE THREAD

**Issue by miaomiao1992** [ZihanType/predawn#2]

**Comment by ZihanType** [comment]
`axum` 和 `actix-web` 的实现，不能满足我的要求，比如自动依赖注入、OpenAPI 文档生成。而且其本身有一些设计缺陷，比如你可以看看另一个 web 框架 `pavex` 的作者写的一篇关于错误处理的文章，[Rust web frameworks have subpar error reporting](https://www.lpalmieri.com/posts/rust-web-frameworks-have-subpar-error-reporting/)，至少在错误处理上，我自认为 `predawn` 的设计要更好一些，当然，这主要是因为我站在前人的肩膀上。
