### ISSUE TITLE
大佬，如何解决循环依赖问题？

### ISSUE THREAD

**Issue by miaomiao1992** [ZihanType/predawn#3]
如果Struct A内部有Struct B，B内部也有A，咋整？

**Comment by ZihanType** [comment]
1. 抛开依赖注入，这个结构体能不能在 Rust 中定义出来，如果不能，这不是依赖注入的问题。
2. 依赖注入，是在 [rudi](https://github.com/ZihanType/rudi) 中解决，不是在这个 crate 解决。
3. rudi 中没有也没有解决循环依赖的问题，只是有一个判断，如果发现 A 依赖 B，B 又依赖 A，即 A 依赖了 A，就会提前 panic，并打印出清晰的错误信息。
4. Spring Boot 能解决，是因为 Java 的引用类型都类似于 Rust 的中的 Option<Box<T>>，你要是在 Rust 中都这么写，也不是不能解决。即便如此，在 Spring Boot 2.6 中，也默认禁止了循环依赖。
5. 循环依赖，表现的是代码质量低下，没有做好整体设计，不能指望由框架来擦屁股。至少在我有限的经验中，还没有遇到必须要使用循环依赖才能解决的问题。如果你有非要使用循环依赖才能解决问题的场景，也可以告知我，我会尝试解决。
