### ISSUE TITLE
ioc

### ISSUE THREAD

**Issue by casemcx** [ZihanType/predawn#4]
能实现ioc容器吗？非常期待ioc

**Comment by ZihanType** [comment]
predawn 使用已经存在的依赖注入库，[rudi](https://github.com/ZihanType/rudi)

**Comment by casemcx** [comment]
有配置自动扫描吗？

**Comment by ZihanType** [comment]
有，你可以看看[examples](https://github.com/ZihanType/rudi/tree/main/examples)

**Comment by casemcx** [comment]
ok，谢谢您的付出

**Comment by casemcx** [comment]
有无明显的问题，我想尝试使用他用在公司的一个边缘服务中，刚开始接触rust

**Comment by ZihanType** [comment]
目前没有，但是功能肯定没有 Spring 那么全。而且没有必要非要使用某个库，还是看实际使用场景。

**Comment by casemcx** [comment]
好的，只是一个简单的微应用，想尝试一下rust的使用
